# Generated by Django 5.2.4 on 2025-08-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["amount"],
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.RenameField(
            model_name="wallet",
            old_name="balance",
            new_name="amount",
        ),
    ]
